SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, (SUM(s.SALES * b.PRICE)) AS TOTAL_SALES
FROM BOOK b 
    JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
    JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID   
WHERE YEAR(s.SALES_DATE) = '2022' AND MONTH(s.SALES_DATE) = '01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC