SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM (
        SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
        FROM FISH_INFO     
        GROUP BY FISH_TYPE
    ) AS M
    JOIN FISH_INFO AS I
        ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
    JOIN FISH_NAME_INFO AS N
      ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY I.ID;
    
